# ──────────────────────────────────────────────────────────────────────────────
# Namespace for all demo apps
# ──────────────────────────────────────────────────────────────────────────────
apiVersion: v1
kind: Namespace
metadata:
  name: demo
