apiVersion: v1
kind: Namespace
metadata:
  name: alpine-sit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-sit
  namespace: alpine-sit
  labels:
    app.kubernetes.io/name: alpine
    environment: sit
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alpine
      environment: sit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alpine
        environment: sit
    spec:
      containers:
        - name: alpine
          image: alpine:3.20
          command:
            - /bin/sh
            - -c
          args:
            - while true; do echo "alpine sit demo is running"; sleep 30; done
          resources:
            requests:
              cpu: 256m
              memory: 32Mi
            limits:
              cpu: 256m
              memory: 64Mi
