skipMysql: true
mysql:
  host: my-dongtai-mysql
  port: 3306
  name: my-dongtai_webapi
  user: root
  password: my-dongtai-iast

skipRedis: true
redis:
  host: my-dongtai-redis
  port: 6379
  password: 123456
  db: 0