apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-ai-gateway-basic
  namespace: default
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        container:
          # Note: this is to clear the large default memory/cpu requirements for local tests.
          # In production, you should set these to values that make sense for your environment.
          resources: {}
