pipelineJob('devsecops-demo-pipeline') {
  description('Demo DevSecOps pipeline job generated by Job DSL.')

  logRotator {
    numToKeep(5)
  }

  parameters {
    stringParam('IMAGE_TAG', '', 'Docker image tag (defaults to git commit SHA if left empty)')
  }

  definition {
    cpsScm {
      scm {
        git {
          remote {
            // Update this URL to your repo before running the job.
            url('https://github.com/tanut-pen/dev-sec-ops.git')
            credentials('tanut-pen')
          }
          branch('*/main')
        }
      }
      scriptPath('apps/jenkins/demo/Jenkinsfile')
      lightweight(true)
    }
  }
}
