apiVersion: v1
kind: Pod
spec:
  containers:
  # Golang container for tests and modules
  - name: golang
    image: golang:1.22-alpine
    command:
    - cat
    tty: true
  
  # Sonar Scanner container
  - name: sonar
    image: sonarsource/sonar-scanner-cli:latest
    command:
    - cat
    tty: true

  # Docker CLI container
  - name: docker-cli
    image: docker:cli
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  
  # Trivy scan container
  - name: trivy
    image: aquasec/trivy:0.69.3
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock 
      name: docker-sock
  
  # Container for API requests
  - name: curl
    image: alpine:latest
    command:
    - cat
    tty: true

  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
