apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-dbless-config
  namespace: kong
data:
  kong.yml: |
    _format_version: "3.0"
    upstreams:
    - algorithm: round-robin
      hash_fallback: none
      hash_on: none
      hash_on_cookie_path: /
      healthchecks:
        active:
          concurrency: 10
          healthy:
            http_statuses:
            - 200
            - 302
            interval: 0
            successes: 0
          http_path: /
          https_verify_certificate: true
          timeout: 1
          type: http
          unhealthy:
            http_failures: 0
            http_statuses:
            - 429
            - 404
            - 500
            - 501
            - 502
            - 503
            - 504
            - 505
            interval: 0
            tcp_failures: 0
            timeouts: 0
        passive:
          healthy:
            http_statuses:
            - 200
            - 201
            - 202
            - 203
            - 204
            - 205
            - 206
            - 207
            - 208
            - 226
            - 300
            - 301
            - 302
            - 303
            - 304
            - 305
            - 306
            - 307
            - 308
            successes: 0
          type: http
          unhealthy:
            http_failures: 0
            http_statuses:
            - 429
            - 500
            - 503
            tcp_failures: 0
            timeouts: 0
        threshold: 0
      name: kong
      slots: 10000
      use_srv_name: false

    services:
    - connect_timeout: 10000
      enabled: true
      host: echo.demo.svc.cluster.local
      name: echo-service
      port: 80
      protocol: http
      read_timeout: 10000
      retries: 3
      write_timeout: 10000
      routes:
      - https_redirect_status_code: 426
        name: echo-route
        path_handling: v0
        paths:
        - /echo
        preserve_host: false
        protocols:
        - http
        - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: true
    - connect_timeout: 10000
      enabled: true
      host: httpbin.demo.svc.cluster.local
      name: httpbin-service
      port: 80
      protocol: http
      read_timeout: 10000
      retries: 3
      write_timeout: 10000
      routes:
      - https_redirect_status_code: 426
        name: httpbin-route
        path_handling: v0
        paths:
        - /httpbin
        preserve_host: false
        protocols:
        - http
        - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: true
