apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: devsecops-lab
  # Finalizer ensures child apps are deleted when root app is deleted
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tanut-pen/dev-sec-ops.git
    targetRevision: HEAD
    path: argocd
    directory:
      include: "envoy.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true       # remove Applications deleted from app-list.yaml
      selfHeal: true    # re-apply if someone manually changes the cluster
    syncOptions:
      - CreateNamespace=true
