---
# ── Demo Services ─────────────────────────────────────────────────────────────
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-services
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: devsecops-lab
spec:
  revisionHistoryLimit: 3
  project: default
  source:
    repoURL: https://github.com/tanut-pen/dev-sec-ops.git
    targetRevision: HEAD
    path: apps/custom_microservice
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true