apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: devsecops-lab
    app.kubernetes.io/name: envoy
spec:
  revisionHistoryLimit: 3
  project: default
  source:
    repoURL: https://github.com/tanut-pen/dev-sec-ops.git
    targetRevision: HEAD
    path: apps/envoy/deployment
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true