apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ollama-qwen

resources:
  - deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: devsecops-lab
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
