apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: harbor
  namespace: harbor
spec:
  hosts:
    - harbor.tpinf.xyz
  http:
    # Token endpoint — must allow ALL methods especially POST
    - match:
        - uri:
            prefix: /service/token
      route:
        - destination:
            host: my-harbor-core
            port:
              number: 80

    # Registry API — blob uploads
    - match:
        - uri:
            prefix: /v2/
      route:
        - destination:
            host: my-harbor-core
            port:
              number: 80
      timeout: 300s                     # long timeout for big image pushes

    # Core API
    - match:
        - uri:
            prefix: /api/
      route:
        - destination:
            host: my-harbor-core
            port:
              number: 80

    - match:
        - uri:
            prefix: /c/
      route:
        - destination:
            host: my-harbor-core
            port:
              number: 80

    - match:
        - uri:
            prefix: /service/
      route:
        - destination:
            host: my-harbor-core
            port:
              number: 80

    # Portal — catch all
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: my-harbor-portal
            port:
              number: 80