_format_version: "3.0"
services:
- connect_timeout: 60000
  enabled: true
  host: argocd-server.argocd.svc.cluster.local
  name: argocd
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: argocd-route
    path_handling: v0
    paths:
    - /argocd
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: defectdojo-django.defectdojo.svc.cluster.local
  name: defectdojo
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: defectdojo-route
    path_handling: v0
    paths:
    - /defectdojo
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: grafana-grafana.grafana.svc.cluster.local
  name: grafana
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: grafana-route
    path_handling: v0
    paths:
    - /grafana
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: my-harbor-portal.harbor.svc.cluster.local
  name: harbor
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: harbor-route
    path_handling: v0
    paths:
    - /harbor
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: jenkins.jenkins.svc.cluster.local
  name: jenkins
  port: 8080
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: jenkins-route
    path_handling: v0
    paths:
    - /jenkins
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: portainer.portainer.svc.cluster.local
  name: portainer
  port: 9000
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: portainer-route
    path_handling: v0
    paths:
    - /portainer
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: sonarqube-sonarqube.sonarqube.svc.cluster.local
  name: sonarqube
  port: 9000
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: sonarqube-route
    path_handling: v0
    paths:
    - /sonarqube
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: uptime-kuma.monitoring.svc.cluster.local
  name: uptime-kuma
  port: 3001
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: uptime-kuma-route
    path_handling: v0
    paths:
    - /uptime-kuma
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: vault.default.svc.cluster.local
  name: vault
  port: 8200
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: vault-route
    path_handling: v0
    paths:
    - /vault
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
