_format_version: "3.0"
consumers:
- keyauth_credentials:
  - key: my-secret-api-key
  username: demo-user
services:
- connect_timeout: 10000
  enabled: true
  host: echo.demo.svc.cluster.local
  name: echo-service
  plugins:
  - config:
      add:
        body: []
        headers:
        - X-Forwarded-By:kong-gateway
        - X-Demo-Service:echo
        querystring: []
      append:
        body: []
        headers: []
        querystring: []
      http_method: null
      remove:
        body: []
        headers: []
        querystring: []
      rename:
        body: []
        headers: []
        querystring: []
      replace:
        body: []
        headers: []
        querystring: []
        uri: null
    enabled: true
    name: request-transformer
    protocols:
    - grpc
    - grpcs
    - http
    - https
  port: 80
  protocol: http
  read_timeout: 10000
  retries: 3
  routes:
  - https_redirect_status_code: 426
    name: echo-route
    path_handling: v0
    paths:
    - /echo
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 10000
- connect_timeout: 10000
  enabled: true
  host: httpbin.demo.svc.cluster.local
  name: httpbin-secure-service
  plugins:
  - config:
      anonymous: null
      hide_credentials: true
      key_in_body: false
      key_in_header: true
      key_in_query: true
      key_names:
      - apikey
      realm: null
      run_on_preflight: true
    enabled: true
    name: key-auth
    protocols:
    - grpc
    - grpcs
    - http
    - https
  - config:
      day: null
      error_code: 429
      error_message: API rate limit exceeded
      fault_tolerant: true
      header_name: null
      hide_client_headers: false
      hour: null
      limit_by: consumer
      minute: 30
      month: null
      path: null
      policy: local
      redis:
        database: 0
        host: null
        password: null
        port: 6379
        server_name: null
        ssl: false
        ssl_verify: false
        timeout: 2000
        username: null
      redis_database: 0
      redis_host: null
      redis_password: null
      redis_port: 6379
      redis_server_name: null
      redis_ssl: false
      redis_ssl_verify: false
      redis_timeout: 2000
      redis_username: null
      second: null
      sync_rate: -1
      year: null
    enabled: true
    name: rate-limiting
    protocols:
    - grpc
    - grpcs
    - http
    - https
  port: 80
  protocol: http
  read_timeout: 10000
  retries: 3
  routes:
  - https_redirect_status_code: 426
    name: secure-route
    path_handling: v0
    paths:
    - /secure
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 10000
- connect_timeout: 10000
  enabled: true
  host: httpbin.demo.svc.cluster.local
  name: httpbin-service
  plugins:
  - config:
      day: null
      error_code: 429
      error_message: API rate limit exceeded
      fault_tolerant: true
      header_name: null
      hide_client_headers: false
      hour: null
      limit_by: ip
      minute: 10
      month: null
      path: null
      policy: local
      redis:
        database: 0
        host: null
        password: null
        port: 6379
        server_name: null
        ssl: false
        ssl_verify: false
        timeout: 2000
        username: null
      redis_database: 0
      redis_host: null
      redis_password: null
      redis_port: 6379
      redis_server_name: null
      redis_ssl: false
      redis_ssl_verify: false
      redis_timeout: 2000
      redis_username: null
      second: null
      sync_rate: -1
      year: null
    enabled: true
    name: rate-limiting
    protocols:
    - grpc
    - grpcs
    - http
    - https
  - config:
      add:
        body: []
        headers:
        - X-Forwarded-By:kong-gateway
        - X-Demo-Service:httpbin
        querystring: []
      append:
        body: []
        headers: []
        querystring: []
      http_method: null
      remove:
        body: []
        headers: []
        querystring: []
      rename:
        body: []
        headers: []
        querystring: []
      replace:
        body: []
        headers: []
        querystring: []
        uri: null
    enabled: true
    name: request-transformer
    protocols:
    - grpc
    - grpcs
    - http
    - https
  port: 80
  protocol: http
  read_timeout: 10000
  retries: 3
  routes:
  - https_redirect_status_code: 426
    name: httpbin-route
    path_handling: v0
    paths:
    - /httpbin
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 10000
