properties([
    parameters([
        booleanParam(name: 'PUSH_TO_HARBOR', defaultValue: false, description: 'Push the built image to Harbor'),
        booleanParam(name: 'IMPORT_TO_DEFECTDOJO', defaultValue: false, description: 'Upload the Trivy report to DefectDojo')
    ])
])

// Load and run the pipeline logic from the library script
def pipelineLib = load 'jenkins/lib/pipeline.groovy'
pipelineLib.run()
