pipelineJob('devsecops-demo-pipeline') {
  description('Demo DevSecOps pipeline job generated by Job DSL.')

  parameters {
    booleanParam('PUSH_TO_HARBOR', false, 'Push the built image to Harbor')
    booleanParam('IMPORT_TO_DEFECTDOJO', false, 'Upload Trivy report to DefectDojo')
  }

  definition {
    cpsScm {
      scm {
        git {
          remote {
            // Update this URL to your repo before running the job.
            url('https://github.com/tanut-pen/dev-sec-ops.git')
            credentials('tanut-pen')
          }
          branch('*/main')
        }
      }
      scriptPath('jenkins/demo/Jenkinsfile')
      lightweight(true)
    }
  }
}
